version: "3"

services:
  db:
    image: mongo:latest
    restart: "always"
    ports:
      - "27017:27017"

  rest-api:
    build: ./rest-service/
    depends_on:
      - db
    ports:
      - "5000:5000"
    links:
      - db

  angular:
    build: ./notes-webapp/
    depends_on:
      - db
      - rest-api
    ports:
      - "4200:4200"
    volumes:
      - "./notes-webapp:/notes-webapp/"
      - "/notes-webapp/node_modules"