apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: nodejs-builder
  name: nodejs-builder
spec:
  source:
    image: node:12-alpine
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-builder:latest
  triggers:
  - type: ConfigChange
  - imageChange:
      type: ImageChange
